### ISSUE TITLE
重庆图书馆数据能支持一下吗

### ISSUE THREAD

**Issue by DemoJ** [wyj0605/douban_library#1]
如题，十分感谢

**Comment by wyj0605** [comment]
![image](https://github.com/wyj0605/douban_library/assets/2581073/0a302045-076e-40a3-a2ed-b75cb79d1fce)
已支持重庆市图书馆，已提交插件商店等待审核。

**Comment by DemoJ** [comment]
大写的感谢！

**Comment by wyj0605** [comment]
已支持重庆市图书馆。
