### ISSUE TITLE
能不能增加南京图书馆啊。

### ISSUE THREAD

**Issue by pwj1568** [wyj0605/douban_library#2]
南图，不是南京金陵图书馆，本质上它应该叫江苏省图书馆。
http://www.jslib.org.cn/

**Comment by wyj0605** [comment]
已增加南京市图书馆。南京金陵图书馆更改为江苏省图书馆
![image](https://github.com/wyj0605/douban_library/assets/2581073/5032ddcb-e895-42cb-b235-851aa1db229b)

**Comment by pwj1568** [comment]
啊，你搞错了吧，可能还是我表达的不清楚。

南京金陵图书馆（http://www.jllib.org.cn/），又名南京市立图书馆。
南京图书馆（http://www.jslib.org.cn/），简称南图，它属于江苏省的，比南京金陵图书馆大多了。
本质上，前者是市立，后者是省立。差了一个级别。

这个插件之前只支持南京金陵图书馆，我上次说了之后，你改的是把金陵图书馆改成江苏省图书馆，现在这个图书馆选择列表里面有“江苏省”和“南京市”，但是你给搞反了，你把“南京市”这个对应成了南京图书馆（南图，省立图书馆），把“江苏省”这个对应成了南京金陵图书馆（市立图书馆）。这样就不对了。应该改成“江苏省”对应南京图书馆（南图，省立），“南京市”对应南京金陵图书馆（市立）。

南京图书馆和南京金陵图书馆，之所以容易让人混淆，都是历史遗留的原因。就像南京博物院和南京市博物馆，前者是省立，后者是市立，本质上前者应该叫江苏省博物馆，就像南图应该叫江苏省图书馆一样，只不过官方没有改还沿用了之前的南京命名的名字。

**Comment by wyj0605** [comment]
已更改。

**Comment by pwj1568** [comment]
终于对了。非常感谢。

**Comment by pwj1568** [comment]
你好，问一下，这个查询功能涉及后端知识吗？我想做一个Android端App实现这个查询功能，是不是还得研究研究后端知识啊。

**Comment by wyj0605** [comment]
需要后端编程，分析每个图书馆查询接口，重构成你需要的格式数据。
