### ISSUE TITLE
厦门图书馆接口有误？

### ISSUE THREAD

**Issue by dingar** [wyj0605/douban_library#3]
在图书馆网站可以查到馆藏。但是图书馆查询助手却查询不到。几乎所有书都查不到。

**Comment by wyj0605** [comment]
![image](https://github.com/wyj0605/douban_library/assets/2581073/9156ec43-431b-48fd-82c7-f11a42144ac9)
![image](https://github.com/wyj0605/douban_library/assets/2581073/864641dd-33db-4b06-8481-a37c302838dc)
感谢反馈，厦门图书馆增加了搜索验证功能导致无法访问搜索接口，目前已解决。后续我还会随时关注接口变化情况。

**Comment by wyj0605** [comment]
![image](https://github.com/wyj0605/douban_library/assets/2581073/700df259-5a76-4854-956c-f0f33673ae9c)
厦门图书馆新增了图型验证，还在想办法解决。

**Comment by wyj0605** [comment]
已修复后端访问接口，可以查询图书信息了。
![image](https://github.com/wyj0605/douban_library/assets/2581073/fba7aaf2-b0f6-4b3b-9331-01d8fc2916f2)

**Comment by dingar** [comment]
感谢！
