### ISSUE TITLE
建议显示出图书馆名+地址

### ISSUE THREAD

**Issue by wind8866** [wyj0605/douban_library#4]
青岛市有很多主馆（如李沧图书馆）+社区24小时自助馆（如李沧_世园_城市书房金水东路社区）
建议将馆名+地址显示出才能更好的定位
<img width="1358" alt="image" src="https://github.com/wyj0605/douban_library/assets/36020415/79543733-f664-4cf5-955f-ecff86c1bfe6">

如果在“**豆瓣+图书馆查询助手**”左边加上跳转链接就更好了
http://124.129.202.157/opac/search?&q=9787506365604&searchWay=isbn&sortWay=score&sortOrder=desc&scWay=dim&hasholding=1&searchSource=reader

**Comment by wyj0605** [comment]
已修正图书馆名+馆藏地![image](https://github.com/wyj0605/douban_library/assets/2581073/d8ce970e-a279-4a3d-9cce-50253981ef7d)

**Comment by wyj0605** [comment]
跳转链接后续考虑增加，感谢使用。
