### ISSUE TITLE
希望增加同时查询多个图书馆的功能

### ISSUE THREAD

**Issue by asong2001** [wyj0605/douban_library#5]
感谢支持南宁图书馆和广西图书馆，希望可以同时查询这两个馆。两个图书馆都在南宁市区，同时显示更方便。

**Comment by wyj0605** [comment]
还在考虑前后端的设计，后续会支持多馆查询，

**Comment by wyj0605** [comment]
已支持同时选择两个图书馆功能，近期新版本中会发布。
![image](https://github.com/wyj0605/douban_library/assets/2581073/e7282f1c-0cf4-4703-ae24-b261923346ca)
