### ISSUE TITLE
图书分类号过长时，显示重叠的问题

### ISSUE THREAD

**Issue by gtoo8888** [wyj0605/douban_library#6]
在豆瓣图书搜索人月神话图书的时候，发现索书号非常的长，遮挡掉了后面的是否在管情况
![renyueshenhua](https://github.com/wyj0605/douban_library/assets/33313831/a37dac34-714c-42a5-a861-25bde3e74c13)
![error](https://github.com/wyj0605/douban_library/assets/33313831/807437b5-4b92-43d8-94d1-b75882c2fc99)
看到索书号和在管情况是分成两个div显示的，是否考虑可以隔一行进行显示
![html](https://github.com/wyj0605/douban_library/assets/33313831/e1cbddc1-2141-4aa6-99cc-31cbf961437c)

**Comment by wyj0605** [comment]
发布新版本中会修复此BUG。新版本还会增加同时选择两个图书馆功能。
![image](https://github.com/wyj0605/douban_library/assets/2581073/642b00b6-f9bd-45d9-97d3-31e3bce9ad4f)
